# Generated by Django 4.2 on 2023-04-19 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='price',
        ),
    ]
